# Generated by Django 5.2.1 on 2025-05-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('unqualified', 'Unqualified')], default='new', help_text='Select the status of the lead', max_length=20, verbose_name='Lead Status')),
                ('name', models.CharField(help_text='Enter your full name', max_length=255, verbose_name='Full Name')),
                ('email', models.EmailField(help_text='Enter your email address', max_length=254, verbose_name='Email Address')),
                ('phone', models.CharField(help_text='Enter your phone number', max_length=20, verbose_name='Phone Number')),
                ('Source', models.CharField(help_text='Enter the source of the lead', max_length=255, verbose_name='Lead Source')),
                ('note', models.TextField(blank=True, help_text='Enter any additional notes about the lead', null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
